### PR TITLE
gha:  replace deprecated "set-env", "add-path", update setup-go@v2, update go to 1.15

### PR DESCRIPTION
**Pull request by thaJeztah**
See individual commits for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
@estesp @mxpv ptal

**Comment by thaJeztah** [comment]
Pushed a commit to update the badge in the README, which was still showing Travis status

**Review by Zyqsempai — APPROVED** [review]
LGTM

**Review by estesp — APPROVED** [review]
LGTM

**Pull request merged**
