### PR TITLE
Remove gogo protobuf support

### PR DESCRIPTION
**Pull request by dmcgowan**
Remove Gogo Protobuf support and add a line in Readme about it.

This was previously discussed as not worthy of a major release bump due to the low impact of the change vs refactoring required to keep compatibility between major versions. If the impact is not as low as expected, we will reconsider.

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
Needs rebase

**Review by samuelkarp — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Comment by liggitt** [comment]
is it intentional that this PR has not been included in any release tag yet? the latest tag (2.2.3) still references gogo and means that is in the dependency tree for containerd/containerd and downstreams

**Comment by liggitt** [comment]
can this be picked to the 2.2 branch or a v2.3.0 tag be cut?

**Comment by samuelkarp** [comment]
@liggitt Just cut https://github.com/containerd/typeurl/releases/tag/v2.3.0 for you.

**Pull request merged**
