### PR TITLE
Add containerd project checks to CI

### PR DESCRIPTION
**Pull request by austinvazquez**
Add containerd project checks to CI

Signed-off-by: Austin Vazquez <macedonv@amazon.com>

### CODE REVIEW

**Review by estesp — APPROVED** [review]
LGTM

**Comment by samuelkarp** [comment]
Can we move this repo to use the [project-checks action](https://github.com/containerd/project-checks/) instead?

**Comment by austinvazquez** [comment]
> > Can we move this repo to use the [project-checks action](https://github.com/containerd/project-checks/) instead?
> 
> Hmm, good point. Looks like this subproject never got moved to the project-checks action. @austinvazquez do you mind updating this workflow to use the project-checks?

+1 will update.

**Review by estesp — APPROVED** [review]
LGTM

**Review by dmcgowan — APPROVED** [review]

**Pull request merged**
